version: '3.8'

services:

  # TODO: Requires CORS or internal forwarding (/api/* -> api)
#  front:
#    build:
#      context: ./app/front
#      dockerfile: dev.Dockerfile
#    restart: always
#    volumes:
#      - ./app/front:/app
#    ports:
#      - "8080:8080"
#    working_dir: /app
#    command: npm start

  api:
    build:
      context: ./app/api
      dockerfile: dev.Dockerfile
    restart: always
    volumes:
      - ./app/api:/app
      - ./uploads:/uploads
      - ./app/api/mcuLibs.txt:/data/mcuLibs.txt
    ports:
      - "9090:9090"
    working_dir: /app
    command: sleep 3600000 # lein run