version: '3.8'

services:

  front:
    build:
      context: ./app/front
      dockerfile: dev.Dockerfile
    restart: always
    volumes:
      - ./app/front:/app
    ports:
      - "8080:8080"
    working_dir: /app
    command: npm start